### ISSUE TITLE
[Feature]: make rename popup width customizable

### ISSUE THREAD

**Issue by xeluxee** [filipdutescu/renamer.nvim#101] opened 2021-12-13 19:45 UTC
# Describe the issue
Hi, first of all thanks for this plugin
I think that popup looks small, I'd like it to be wider

## Proposal
Is it possible to increase popup width? Maybe making it configurable by adding an option in `setup()`

**Comment by filipdutescu** [comment] 2021-12-15 21:38
Thanks for the kind words and the request. The popup scales with the word. The bigger it is, the wider the popup. But I can add an option to customise the minimum width, which should suite your needs.

**Comment by xeluxee** [comment] 2021-12-16 17:24
> The popup scales with the word

Yeah the popup scales with word but I can't see the entire word because it gets truncated

![rename-popup1](https://user-images.githubusercontent.com/88047141/146419205-255b0f0c-97be-4392-ba3e-57c01539dcdf.png)
![rename-popup2](https://user-images.githubusercontent.com/88047141/146419291-03245fbc-2944-4573-a88e-8905442c6443.png)

This happens with words that are longer than 7 characters

**Comment by filipdutescu** [comment] 2021-12-16 17:29
I see, this adds better context, thanks for the details! The issue is the maximum length, which I can also make customizable.

**Comment by filipdutescu** [comment] 2021-12-19 12:01
Could you post your `renamer.setup {...}` please? Something seems off. Might be you have right padding.

**Comment by xeluxee** [comment] 2021-12-20 16:35
I'm simply using this
``` lua
require('renamer').setup()
```

**Comment by filipdutescu** [comment] 2021-12-20 21:20
I think some Neovim settings you use might interfere with `renamer`. Does the issue also happen with a "blank" config that only has `renamer` setup?

**Comment by filipdutescu** [comment] 2022-01-03 17:10
I cannot reproduce this behaviour, I am pretty sure this comes from another plugin or maybe from some Neovim settings you are using. I will add the option for minwidth and maxwidth customization, but asides from that, nothing I can do, without additional info.

**Comment by xeluxee** [comment] 2022-01-04 14:49
@filipdutescu thanks, it works

**Comment by xeluxee** [comment] 2022-01-04 14:51
@filipdutescu I've just discovered that my issue was linked to `sidescrolloff` option in Neovim
When I `:set sidescrolloff=0` the word isn't truncated anymore, but a character is missing if it's longer than `min_width`

**Comment by filipdutescu** [comment] 2022-01-04 14:51
Glad all worked out! I still think the issue was another plugin/setting of Neovim. If you manage to figure out by any chance what was causing it, please let me know, maybe another fix is needed. Thanks for using `renamer`!

**Comment by filipdutescu** [comment] 2022-01-04 14:54
I reopened it to do just that. Will close it with the fix. Won't remove the width customization however, as it brings some nice options to users.

**Comment by xeluxee** [comment] 2022-01-04 14:58
> Thanks for using `renamer`!

Thank you for maintaining it!

> but a character is missing if it's longer than `min_width`

Even with `sidescrolloff=0` a character is missing
![renamer-bug](https://user-images.githubusercontent.com/88047141/148078002-108b31d9-d687-48de-b693-08a38c15ed02.png)

**Comment by filipdutescu** [comment] 2022-01-04 14:59
That's expected, if you increase maximum width by 1 it should show up. It is not really meant to show a *huge* word, but with the new options it should make it easy for you to make it behave the way you wish.

**Comment by xeluxee** [comment] 2022-01-04 15:04
Currently I set `max_width` to 50, while that word is 33 characters long.
If i press home key the cursor is brought to line start and the entire word is shown.
I don't know why even if `scrolloff` is 0 there is one blank space after the cursor

**Comment by filipdutescu** [comment] 2022-01-04 15:08
The blank space is there since you are in `insert` mode, but this is weird, the whole word should be shown :thinking:. I wonder if there is another setting that is impacting this or not. I will test it out a bit later, but nice catch. It might also be `plenary.popup`'s behaviour at fault here, but I am not sure about that either.

Seems like a more complex issue than I initially thought.

**Comment by filipdutescu** [comment] 2022-01-10 21:54
@xeluxee do you have any other special option set? like a high `sidescroll` value (for me, `sidescroll=1`)? I cannot figure out where the extra space is from

**Comment by xeluxee** [comment] 2022-01-11 17:17
> @xeluxee do you have any other special option set? like a high `sidescroll` value (for me, `sidescroll=1`)? I cannot figure out where the extra space is from

`sidescroll` is 1 for me too, I think this extra space is linked to insert mode...
Anyway I think setting `sidescrolloff` to 0 locally to renamer popup is enough. I've tried to rename a variable with a long name only for testing purpose, but I think 90% of the time there is no need to interact with such variables.

**Comment by filipdutescu** [comment] 2022-01-15 09:43
Ok, I tried my best to reproduce the space issue as well, but I cannot do it. Honestly not sure where it comes from. I think I will just fix the `sidescrolloff` issue and leave it at that, if I cannot figure anything out in a couple of hours.

**Comment by filipdutescu** [comment] 2022-01-15 09:47
I reproduced the issue, it seems like the popup does not care about the max width option. I think this is a [plenary](https://github.com/nvim-lua/plenary.nvim) issue, from what I can tell. Gonna investigate a bit more.

**Comment by filipdutescu** [comment] 2022-01-15 09:50
Ok I found it, jeez that was a hard one to find haha. If the current word was larger than the default width (popup title length + 4), I would set the width to the word length. But that would evidently truncate 1 character. So I just have to add `+ 1`

**Closed** 2022-01-15 09:55 UTC
Labels: feature

**Comment by xeluxee** [comment] 2022-01-15 20:23
@filipdutescu thanks for your efforts, now it works well 😄

**Comment by filipdutescu** [comment] 2022-01-15 21:37
My pleasure, thanks for using my plugin and sorry for the delay! :grin:
